package main

import (
	"fmt"

	secretsharing "github.com/bytemare/secret-sharing"
	"github.com/bytemare/secret-sharing/keys"
	"github.com/bytemare/ecc"
	"github.com/bytemare/frost"
)

func main() {

	group := ecc.Ristretto255Sha512

	shares, err := secretsharing.Shard(
		group,
		nil, // generate random secret
		3,   // threshold
		5,   // max signers
	)

	if err != nil {
		panic(err)
	}

	fmt.Printf("Generated %d key shares\n\n", len(shares))

	for _, share := range shares {

		fmt.Printf(
			"Signer ID: %d\n",
			share.Identifier(),
		)
	}

	fmt.Println()

	var publicShares []*keys.PublicKeyShare

	for _, share := range shares {

		publicShare := share.Public()

		publicShares = append(
			publicShares,
			publicShare,
		)

		fmt.Printf(
			"Public Share ID: %d\n",
			publicShare.ID,
		)
	}

	fmt.Printf(
		"\nCollected %d public key shares\n",
		len(publicShares),
	)

	fmt.Println()

	for _, share := range shares {

		fmt.Printf(
			"ID=%d PublicExists=%v SecretExists=%v\n",
			share.Identifier(),
			share.Public() != nil,
			share.SecretKey() != nil,
		)
		
	}
	fmt.Println()

for _, share := range shares {

	fmt.Printf(
		"ID=%d VerificationKeyExists=%v\n",
		share.Identifier(),
		share.VerificationKey != nil,
	)
}



fmt.Println()

config := &frost.Configuration{
	Ciphersuite:           frost.Default,
	Threshold:             3,
	MaxSigners:            5,
	VerificationKey:       shares[0].VerificationKey,
	SignerPublicKeyShares: publicShares,
}

err = config.Init()

if err != nil {
	panic(err)
}

fmt.Println("FROST configuration initialized successfully")



fmt.Println()

var signers []*frost.Signer

for i := 0; i < 3; i++ {

	s, err := config.Signer(
		shares[i],
	)

	if err != nil {
		panic(err)
	}

	signers = append(
		signers,
		s,
	)

	fmt.Printf(
		"Created FROST signer with ID %d\n",
		s.Identifier(),
	)
}

fmt.Println()

var commitments frost.CommitmentList

for _, s := range signers {

	c := s.Commit()

	commitments = append(
		commitments,
		c,
	)

	fmt.Printf(
		"Commitment generated by signer %d\n",
		c.SignerID,
	)

	fmt.Printf(
		"Commitment ID: %d\n",
		c.CommitmentID,
	)
}

fmt.Printf(
	"\nTotal Commitments: %d\n",
	len(commitments),
)




fmt.Println()

message := []byte("hello-frost-threshold-signing")

var sigShares []*frost.SignatureShare

for _, s := range signers {

	sigShare, err := s.Sign(
		message,
		commitments,
	)

	if err != nil {
		panic(err)
	}

	sigShares = append(
		sigShares,
		sigShare,
	)

	fmt.Printf(
		"Signature Share generated by signer %d\n",
		sigShare.SignerIdentifier,
	)
}

fmt.Printf(
	"\nTotal Signature Shares: %d\n",
	len(sigShares),
)


commitments.Sort()

signature, err := config.AggregateSignatures(
	message,
	sigShares,
	commitments,
	true,
)

if err != nil {
	panic(err)
}

fmt.Println()
fmt.Println("Threshold signature generated successfully")

fmt.Printf(
	"Signature Group: %v\n",
	signature.Group,
)

}