apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: frost-k8s
servers: 1
agents: 1
options:
  k3s:
    extraArgs:
      - arg: --kube-apiserver-arg=service-account-signing-endpoint=unix:///var/run/frost-k8s/signer.sock
        nodeFilters:
          - server:*
volumes:
  - volume: frost-socket:/var/run/frost-k8s
    nodeFilters:
      - server:*
